apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  APP_KEY: "YmFzZTY0OjhhVnUxczZMVlAyRmgxMzN6WVdMV0Y0NUVseDlDN1ZhY0FSTVpDNEVpVzA9"
  DB_CONNECTION: "bXlzcWw="
  DB_HOST: "aG9zdC5kb2NrZXIuaW50ZXJuYWw="
  DB_PORT: "MzMzMDY="
  DB_DATABASE: "YXBwX2RhdGFiYXNl"
  DB_USERNAME: "YXBwX3VzZXI="
  DB_PASSWORD: "YXBwX3Bhc3N3b3Jk"
  OPENSEARCH_BASE_URL: "aHR0cHM6Ly92cGMtdHJlYy1kZXYtc2VhcmNoLWNsdXN0ZXItNzRkZW40aTR3dmptaW9leXNhZjRvb3pzaTQuZXUtd2VzdC0xLmVzLmFtYXpvbmF3cy5jb20="
  OPENSEARCH_USERNAME: "Zm9ybmFjZQ=="
  OPENSEARCH_PASSWORD: "Q2FtYmlhbWkxMjMh"
  OPENSEARCH_PRODUCTS_INDEX: "cHJvZHVjdHM="
  TRACCIATI_S3_CLIENT_ID: "MmZkZm51YWduNjFscGhkaDlsYWd0Ymk4am4="
  TRACCIATI_S3_SECRET: "MXR1bWpjZzlwN2lramVwamFsdG9pMXFpanJnb2x0c3V2NWZxZ3FmNjJtdWFkbmdxY2h0"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "dXMtZWFzdC0x"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "ZmFsc2U="
  MAIL_MAILER: "c210cA=="
  MAIL_SCHEME: "bnVsbA=="
  MAIL_HOST: "MTI3LjAuMC4x"
  MAIL_PORT: "MTAyNQ=="
  MAIL_USERNAME: "bnVsbA=="
  MAIL_PASSWORD: "bnVsbA=="